### PR TITLE
Use Go Control API

### LINKED ISSUE #19: IPv6 support
Not sure how much of issue it is

### LINKED ISSUE #53: win not work
image

i want use nat ,build a connect for two work's net 。 my user most use win .....

### PR DESCRIPTION
**Pull request by anacrolix**
Fixes #53, #12, #38, resolves #19, and addresses #5.

Instigated by https://github.com/golang/go/issues/9661 being resolved.

Windows has been tested, and could be added to the CI in a subsequent PR.

### CODE REVIEW

File: interface.go [hunk 1]
```diff
@@ -19,100 +19,46 @@ package reuseport
...
 
-// Available returns whether or not SO_REUSEPORT is available in the OS.
-// It does so by attepting to open a tcp listener, setting the option, and
-// checking ENOPROTOOPT on error. After checking, the decision is cached
-// for the rest of the process run.
+// Available returns whether or not SO_REUSEPORT or equivalent behaviour is
+// available in the OS.
 func Available() bool {
-	return available()
+	return true
```
Comment (Stebalien) [inline interface.go]: I'm pretty sure we can't simply assume that reuseport is available.

File: interface.go [hunk 2]
```diff
@@ -19,100 +19,46 @@ package reuseport
...
+		Control:   Control,
+		LocalAddr: nla,
 	}
-
 	return d.Dial(network, raddr)
 }
-
-// Dialer is used to specify the Dial options, much like net.Dialer.
-// We simply wrap a net.Dialer.
-type Dialer struct {
```
Comment (Stebalien) [inline interface.go]: We should probably keep and deprecate this. It's a public interface and it's actually being used externally (unlike the poll package). We don't *have* to (we can bump to 0.2.0 and make a breaking change) but I'd rather keep it around (deprecated) for a while.

To be completely correct, we'll probably need to (a) copy the `net.Dialer` before replacing the `Control` function and (b) chain the control functions.

File: .gx/lastpubver [hunk 3]
```diff
@@ -1 +1 @@
-0.1.19: QmXD921xzL9EDRpD6gRm1cb7Khm8VEpZ3NT3nPK7uTX6Fq
+0.1.19: QmXpK6aZZpAG38T6aSDBiYPU8wvDoHSczWmXurJzr82j4j
```
Comment (Stebalien) [inline .gx/lastpubver]: You can use `gx release patch` instead of `gx publish -f` to release a new version.

File: test/main.go [hunk 4]
```diff
@@ -1,70 +0,0 @@
-package main
```
Comment (Stebalien) [inline test/main.go]: We should keep this. This is a helper binary to check if reuseport is working on the current machine (helps with debugging).

Comment (anacrolix) [reply test/main.go]: I think this is well covered by the unit tests. The example binary was confusing and long-winded.

File: interface.go (hunk 1 above)
Comment (Stebalien) [reply interface.go]: Got it. I'm fine dropping support for linux <= 3.9.

However, let's keep `Available` as we may need to (eventually) support platforms without reuseport support. Given that we already have it and it adds little complexity, we might as well keep it (unless we find the additional complexity a burden).

File: interface.go (hunk 2 above)
Comment (Stebalien) [reply interface.go]: We have one user here: https://github.com/sonm-io/core/blob/c40eaa1a84fdc6faa9d837e9df1b4c16065aa194/insonmnia/npp/net.go#L26. However, they're using go-mod.

See: https://godoc.org/github.com/libp2p/go-reuseport?importers

---

But I'm not going to object as long as we have a patch ready for go-reuseport-transport.

File: test/main.go (hunk 4 above)
Comment (Stebalien) [reply test/main.go]: IIRC, this binary exists for making sure that reuseport works on the local machine (we've had a *lot* of problems with reuseport in the past). We can ship this off to a user to rule out reuseport issues.

Comment (anacrolix) [reply test/main.go]: We can ship the unit test binary, `go test -c`, which will be much more comprehensive and appropriate. I've used this to test with wine.

Comment (Stebalien) [reply test/main.go]: As long as it emits enough information for us to debug.

File: .gx/lastpubver (hunk 3 above)
Comment (anacrolix) [reply .gx/lastpubver]: Does this happen after I merge?

Comment (Stebalien) [reply .gx/lastpubver]: We can do it either after or before (as long as we don't merge anything else first). However, we shouldn't change the hash here until we bump the version number.

Comment (anacrolix) [reply .gx/lastpubver]: How do I import gx hashes from elsewhere without publishing or bumping the version? Specifically https://github.com/libp2p/go-reuseport-transport/commit/143bb39150ed2e4c467ac3d6300a9121ee9e1767 in CI.

Comment (Stebalien) [reply .gx/lastpubver]: You don't? I mean, you can do that for testing but I'd just release a new version (`gx release minor`).

Note: you'll need to *pin* the new hash. I've invited you to the pinbot IRC room.

File: interface.go (hunk 2 above)
Comment (prestonvanloon) [reply interface.go]: This is breaking our CI builds downstream in github.com/prysmaticlabs/prysm

Comment (anacrolix) [reply interface.go]: @prestonvanloon can you link to log for the failed job?

Comment (prestonvanloon) [reply interface.go]: https://travis-ci.org/prysmaticlabs/prysm/jobs/475121335

Comment (prestonvanloon) [reply interface.go]: We are fetching all dependencies from HEAD right now, but this is something we are aiming to move away from as we are frequently broken by upstream changes.

Comment (anacrolix) [reply interface.go]: Consider using gx, or go.mod which I've included in libp2p/go-reuseport-transport#6.

Comment (Stebalien) [reply interface.go]: Note: to be clear, we support using libp2p directly from master with `go get` for now.

---

I should have been clear and said "merge at the same time" instead of "have the patch ready". We should also *document* what dependency systems we support somewhere.
